### PR TITLE
Add support for single-quoted strings and fix stringifying whitespace

### LINKED ISSUE #8: Support for single quoted strings
See https://github.com/hjson/hjson/issues/74

### LINKED ISSUE #18: String fails in PHP but not in js
Thank you for a great library. 

I found an issue. The string

```
{products: [
  {name:'Knife', price: 2.25},
  {name:'Spoon', price: 2.50},
  {name:'Fork', price: 2.99},
]}
``` 

works when I use http://hjson.org/try.html but not when using this library.

### PR DESCRIPTION
**Pull request by dqsully**
Fixes #18 
Fixes #8 

Also now uses double-quoted strings instead of multiline strings for whitespace-only text.

### CODE REVIEW

File: src/HJSON/HJSONParser.php [hunk 1]
```diff
@@ -99,23 +100,28 @@ private function value()
...
+                    return $this->string('\'');
+                }
+                // Falls through on multiline strings
             default:
                 return $this->tfnns();
         }
     }
 
-    private function string()
+    private function string($quote)
```
Comment (peter279k) [inline src/HJSON/HJSONParser.php]: The `$quote` will be the `double` or `single`.

Is it necessary to set the double quote for `$quote` variable by default?

Comment (dqsully) [reply src/HJSON/HJSONParser.php]: No, not really.

Comment (peter279k) [reply src/HJSON/HJSONParser.php]: Ok.
