### PR TITLE
Fix utf8 implementation

### LINKED ISSUE #14: UTF8
Cant use danish characters: Æ, Ø and Å.

### PR DESCRIPTION
**Pull request by dqsully**
Fixes #14 

It looks like everything was built with utf8 strings in mind, but the parser implementation always counted in bytes, not characters. With this fix, `$this->ch` can now be a multi-byte utf8 character, but `$this->at` still counts up bytes. I've hopefully fixed the `next()`, `peek()`, and `error()`, and I think that's all that needs to be fixed, but I would like someone else to go over my changes as well.

Something to note about this code is that the php function `mb_substr` counts in characters whereas `mb_strcut` counts (safely) in bytes. So in several places I will use `mb_substr(mb_strcut($str, $pos), 0, $len)` where `$pos` is in bytes and `$len` is in characters.

### CODE REVIEW

**Comment by peter279k** [comment]
Travis CI build is failed because of the syntax error.

It should be fixed.

**Comment by dqsully** [comment]
Oh yeah... whoops. Thanks

File: tests/HJSONParserTest.php [hunk 1]
```diff
@@ -10,7 +10,7 @@
 class HJSONParserTest extends TestCase
 {
 
-    public function setUp()
+    protected function setUp(): void
```
Comment (peter279k) [inline tests/HJSONParserTest.php]: If using the `:void` type hint, it should let this package require `php-7.1` version at least.

Comment (dqsully) [reply tests/HJSONParserTest.php]: So the latest version of phpunit (8.0.2) has strict typing and requires this type annotation. Also, even the last-supported version of phpunit doesn't support older than PHP 7.1: https://phpunit.de/announcements/phpunit-7.html. I've made an issue about dropping support for older PHP versions at #20.

Comment (peter279k) [reply tests/HJSONParserTest.php]: It makes sense, but it need to set the required PHP version in `composer.json`.

I think we should write the new released draft when make the latest release.

Comment (dqsully) [reply tests/HJSONParserTest.php]: I suppose this should really be in a separate pull request anyway.

Comment (peter279k) [reply tests/HJSONParserTest.php]: @dqsully, sure.

And it should let the Travis CI build be passed firstly.

File: tests/HJSONParserTest.php [hunk 2]
```diff
@@ -10,7 +10,7 @@
 class HJSONParserTest extends TestCase
 {
 
-    protected function setUp(): void
+    public function setUp()
```
Comment (peter279k) [inline tests/HJSONParserTest.php]: According to the [PHPUnit fixture sample code](https://phpunit.readthedocs.io/en/8.0/fixtures.html?highlight=setUp), the `setUp` method should be `protected`, not `public`.

Comment (peter279k) [reply tests/HJSONParserTest.php]: Here is the [fixture sample code](https://phpunit.de/manual/6.5/en/fixtures.html) for `PHPUnit 6.5`.

It's also the `protected`, not `public`.

**Comment by dqsully** [comment]
Somewhere I must have introduced an infinite loop, because the tests aren't completing anymore. I have to sleep though so I'll take a look at it tomorrow.

**Comment by dqsully** [comment]
Alright, all the tests are passing now. Somehow VS Code didn't quite commit the lines I selected properly, so I had to re-commit some code for the new `error()` implementation. Otherwise, the problem seemed to boil down to the new `peek()` implementation, because I didn't expect a negative offset to be passed in.

**Comment by sustained** [comment]
Thanks for fixing this issue, I'll give the library another try later and report back if I run into any more UTF-8-related issues.

File: src/HJSON/HJSONParser.php [hunk 3]
```diff
@@ -308,6 +308,7 @@ private function error($m)
 
         $i = $this->at;
         while ($i > 0) {
+            $ch = mb_substr(mb_strcut($this->text, $i - 1), 0, 1);
```
Comment (peter279k) [inline src/HJSON/HJSONParser.php]: I think using the `mbstring` functions could solve the `utf-8` issues.

File: src/HJSON/HJSONParser.php [hunk 4]
```diff
@@ -308,6 +308,7 @@ private function error($m)
...
             $i -= strlen($ch);
```
Comment (peter279k) [inline src/HJSON/HJSONParser.php]: I only confused about this.

It looks like some places using the `mb_*` functions and some places don't use.

I think it should use the `mb_*` functions for all source codes because of consistency and it will avoid some issues.

Comment (dqsully) [reply src/HJSON/HJSONParser.php]: The only reason I use `strlen` in that area is because `$i` and `$this->at` are counting in bytes instead of characters. Most of the `mbstring` library functions (except for `mb_strcut`) count in characters. It is generally faster and more efficient to use byte indexes instead of character indexes, so I compromise by letting `$ch` represent a utf8 character but increment `$i` by the number of bytes in `$ch`.

The reason `mbstring` implementations can be less efficient is because utf8 characters can vary in length, so `mbstring` has to start from the beginning of the string and search until it finds its desired character(s). However, ideally normal string functions can index directly into the middle of a string since bytes are of constant length.

For example, [`mb_substr`](http://php.net/manual/en/function.mb-substr.php#117764) has to loop through the entire string from the beginning until it finds the character index you are looking for. However, I think the normal `substr` function is more efficient than that. Feel free to correct me if I've mistaken.

I think eventually doing a smart split like qbolec said on the [`mb_substr`](http://php.net/manual/en/function.mb-substr.php#117764) page would help a lot with efficiency, but that would require a major overhaul of most of the parser code.

Comment (peter279k) [reply src/HJSON/HJSONParser.php]: Hi @dqsully, thank you for your reply.

It makes sense.

Some works need to use the `strlen` to calculate the bytes and others need to use `mb_strlen` to calculate characters.

Final part that you mention is about using the `mb_substr` to be more efficient than `substr`, but how many works should be changed on this pacakge?

I think the final part can have the another issue and it's not related to this issue currently.
